[package]
name = "porcupine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
ctrlc = "3.1.9"
hound = "3.4.0"
itertools = "0.11.0"
pv_porcupine = "=2.2.1"
pv_recorder = "=1.2.0"
dotenv = "0.15.0"